apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e7n9so43t-nodejs
  janus-idp.io/tekton: e7n9so43t-nodejs
  backstage.io/kubernetes-id: e7n9so43t-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e7n9so43t-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
